CREATE TABLE "admission" (
	"id" serial PRIMARY KEY NOT NULL,
	"class" varchar(50) NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100),
	"gender" varchar(20) NOT NULL,
	"mobile_number" varchar(20),
	"email" varchar(100) NOT NULL,
	"student_photo_url" text,
	"date_of_birth" date NOT NULL,
	"father_name" varchar(100),
	"mother_name" varchar(100),
	"guardian_type" varchar(20) NOT NULL,
	"guardian_name" varchar(100) NOT NULL,
	"guardian_relation" varchar(50) NOT NULL,
	"guardian_email" varchar(100),
	"guardian_photo_url" text,
	"guardian_phone" varchar(20),
	"guardian_occupation" varchar(100),
	"guardian_address" text,
	"is_guardian_address_current" boolean DEFAULT false,
	"current_address" text,
	"is_permanent_address_current" boolean DEFAULT false,
	"permanent_address" text,
	"national_id_number" varchar(50),
	"local_id_number" varchar(50),
	"previous_school_details" text,
	"documents_url" text,
	"created_at" date DEFAULT now(),
	"updated_at" date DEFAULT now()
);
